export const worldNFTABI = [
  {
    type: "constructor",
    stateMutability: "nonpayable",
    inputs: [
      { type: "string", name: "name", internalType: "string" },
      { type: "address", name: "_weth", internalType: "address" },
    ],
  },
  {
    type: "event",
    name: "MetaTransactionExecuted",
    inputs: [
      {
        type: "address",
        name: "userAddress",
        internalType: "address",
        indexed: false,
      },
      {
        type: "address",
        name: "relayerAddress",
        internalType: "address payable",
        indexed: false,
      },
      {
        type: "bytes",
        name: "functionSignature",
        internalType: "bytes",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "AddModerator",
    inputs: [
      { type: "address", name: "_newModerator", internalType: "address" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "ChangeOwner",
    inputs: [
      { type: "address", name: "_newOwner", internalType: "address payable" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "string", name: "", internalType: "string" }],
    name: "ERC712_VERSION",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "Kill",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint8", name: "", internalType: "uint8" }],
    name: "STAT_COUNT",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint8", name: "", internalType: "uint8" }],
    name: "STAT_MAX",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "burnMonster",
    inputs: [{ type: "uint64", name: "_tokenId", internalType: "uint64" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [{ type: "uint256", name: "tokenId", internalType: "uint256" }],
    name: "catchMonster",
    inputs: [
      { type: "address", name: "_player", internalType: "address" },
      { type: "uint32", name: "_classId", internalType: "uint32" },
      { type: "string", name: "_name", internalType: "string" },
      { type: "uint256", name: "amount", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "catchMonsterNFT",
    inputs: [
      { type: "uint32", name: "_classId", internalType: "uint32" },
      { type: "string", name: "_name", internalType: "string" },
      { type: "uint256", name: "amount", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "address", name: "", internalType: "address" }],
    name: "dataContract",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "payable",
    outputs: [{ type: "bytes", name: "", internalType: "bytes" }],
    name: "executeMetaTransaction",
    inputs: [
      { type: "address", name: "userAddress", internalType: "address" },
      { type: "bytes", name: "functionSignature", internalType: "bytes" },
      { type: "bytes32", name: "sigR", internalType: "bytes32" },
      { type: "bytes32", name: "sigS", internalType: "bytes32" },
      { type: "uint8", name: "sigV", internalType: "uint8" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "gapFactor",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "pure",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "getChainId",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "bytes32", name: "", internalType: "bytes32" }],
    name: "getDomainSeperator",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      { type: "uint256", name: "", internalType: "uint256" },
      { type: "uint256", name: "", internalType: "uint256" },
      { type: "uint256", name: "", internalType: "uint256" },
      { type: "bool", name: "", internalType: "bool" },
    ],
    name: "getMonsterClassBasic",
    inputs: [{ type: "uint32", name: "_classId", internalType: "uint32" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "nonce", internalType: "uint256" }],
    name: "getNonce",
    inputs: [{ type: "address", name: "user", internalType: "address" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      { type: "bool", name: "catchable", internalType: "bool" },
      { type: "uint256", name: "price", internalType: "uint256" },
    ],
    name: "getPrice",
    inputs: [{ type: "uint32", name: "_classId", internalType: "uint32" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "getRandom",
    inputs: [
      { type: "address", name: "_player", internalType: "address" },
      { type: "uint256", name: "_block", internalType: "uint256" },
      { type: "uint256", name: "_count", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "bool", name: "", internalType: "bool" }],
    name: "isMaintaining",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "mintMonster",
    inputs: [
      { type: "uint32", name: "_classId", internalType: "uint32" },
      { type: "address", name: "_trainer", internalType: "address" },
      { type: "string", name: "_name", internalType: "string" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "bool", name: "", internalType: "bool" }],
    name: "moderators",
    inputs: [{ type: "address", name: "", internalType: "address" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "address", name: "", internalType: "address" }],
    name: "monsterNFT",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "address", name: "", internalType: "address payable" }],
    name: "owner",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "priceIncreasingRatio",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setAddressWhitelist",
    inputs: [
      { type: "address", name: "_smartcontract", internalType: "address" },
      { type: "bool", name: "_status", internalType: "bool" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setClassWhitelist",
    inputs: [
      { type: "uint32", name: "_classId", internalType: "uint32" },
      { type: "bool", name: "_status", internalType: "bool" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setConfig",
    inputs: [
      { type: "uint256", name: "_gapFactor", internalType: "uint256" },
      {
        type: "uint256",
        name: "_priceIncreasingRatio",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "setContract",
    inputs: [
      { type: "address", name: "_dataContract", internalType: "address" },
      { type: "address", name: "_monsterNFT", internalType: "address" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint16", name: "", internalType: "uint16" }],
    name: "totalModerators",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "address", name: "", internalType: "contract IERC20" }],
    name: "weth",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "withdrawEther",
    inputs: [
      { type: "address", name: "_sendTo", internalType: "address" },
      { type: "uint256", name: "_amount", internalType: "uint256" },
    ],
  },
];
export const worldNFTAddress = "0x6648c02de63a033460dCBb4c0812D63411DC8009";
